.TH lxqt-panel "1" "August 2025" "LXQt 2.3.0" "LXQt Panel Module"
.SH NAME
lxqt-panel \- Desktop panel for \fBLXQt\fR: The Lightweight Qt Desktop Environment
.SH SYNOPSIS
.B lxqt-panel [OPTION]
.br
.SH OPTIONS
-h, --help                          Displays help on commandline options.
.br
--help-all                          Displays help, including generic Qt options.
.br
-v, --version                       Displays version information.
.br
-c, --config, --configfile  <file>  Use specific configuration file.
.SH DESCRIPTION
This module adds one or more panel(s) with optional plugins to the desktop.
.SH BEHAVIOR
Under LXQt the panel module is started automatically and by default a horizontal bottom
panel is created on the desktop, containing several plugins: fancymenu, desktopswitch,
quicklaunch, taskbar, statusnotifier, tray, mount, volume, worldclock, showdesktop.
.P
The panel can be run independently of \fBLXQt\fR, autostarted at logon.
.SH CONFIGURATION
Position, alignment, size, autohide, transparency (requires compositor), and other
attributes are configurable by right click.
.P
The panel is comprised of plugins which provide a visual widget. They can be added, moved
or removed in the panel widget settings and by right click menu on the widget itself.
.SH "REPORTING BUGS"
Report bugs to https://github.com/lxqt/lxqt-panel/issues
.SH "SEE ALSO"
.\" any module must refer to the session application, for module overview and initiation
\fBlxqt-session.1\fR  General LXQt overview
.P
\fBlxqt-config-session.1\fR Session Settings
.P
\fBlxqt-config.1\fR  LXQt Configuration Center
.P
